/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CypherSentence: typeof import('./src/components/CypherSentence.vue')['default']
    CypherWord: typeof import('./src/components/CypherWord.vue')['default']
    EdgarsTerminal: typeof import('./src/components/EdgarsTerminal.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
